/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  infraSidebar: [
    {
      type: "category",
      label: "Kubernetes",
      items: [
        { 
          type: "category",
          label: "📙Mastering Kubernetes 3rd ed.",
          items: [
            "k8s/MasteringKubernetes3rd/Motivation_230407_oo01/Motivation_230407_oo01",
            {
              type: "category",
              label: "Chapter 1",
              items: [
                "k8s/MasteringKubernetes3rd/Chap1/WhatIs_230407_oo01/WhatIs_230407_oo01",
                "k8s/MasteringKubernetes3rd/Chap1/Concepts_230407_oo01/Concepts_230407_oo01",
                "k8s/MasteringKubernetes3rd/Chap1/Pod_230407_oo01/Pod_230407_oo01",
                "k8s/MasteringKubernetes3rd/Chap1/Labels_230407_oo01/Labels_230407_oo01",
                "k8s/MasteringKubernetes3rd/Chap1/Service_230407_oo01/Service_230407_oo01",
                "k8s/MasteringKubernetes3rd/Chap1/Volume_230407_oo01/Volume_230407_oo01",
              ],
            },
            {
              type: "category",
              label: "Chapter 2",
              items: [
                 "k8s/MasteringKubernetes3rd/Chap2/Creating_230407_oo01/Creating_230407_oo01",
              ]
            },
          ]
        },
        {
          type: "category",
          label: "Ezmeral",
          items: [
            "k8s/Ezmeral/sec_Overview/Portfolio_220914_oo01/Portfolio_220914_oo01",
            "k8s/Overview/k8sInfo_230112_oo01/k8sInfo_230112_oo01",
          ]
        }
      ]
    },
  ] 

};
